### ISSUE TITLE
Errors if /data/local/tmp/stoic/dev_jar doesn't already exist

### ISSUE THREAD

**Issue by PhilGlass** [square/stoic#11]
If I run `stoic --pkg my.package scratch` (at dfd17465e55129600a68d32e29a213838a1d7142 on an API 34 Pixel 7) I get this:

```
rsync: [Receiver] change_dir#3 "/data/local/tmp/stoic/dev_jar" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(829) [Receiver=3.3.0-20-g4592aa77]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/Library/BuildRoots/4ff29661-3588-11ef-9513-e2437461156c/Library/Caches/com.apple.xbs/Sources/rsync/rsync/io.c(453) [sender=2.6.9]
com.square.stoic.common.FailedExecException: Failed command: 'listOf("rsync", "--blocking-io", "--rsh=sh /Users/philglass/Dev/Repos/stoic/out/rel/script/arsync-wrapper.sh", "/Users/philglass/.config/stoic/plugin/scratch/build/libs/scratch.dex.jar", "adb:/data/local/tmp/stoic/dev_jar/scratch.dex.jar")', exitCode=12, error output:
---
---
	at com.square.stoic.common.StoicKt.runCommand(Stoic.kt:95)
	at com.square.stoic.common.StoicKt.runCommand$default(Stoic.kt:58)
	at com.square.stoic.host.main.HostMainKt.arsync(HostMain.kt:359)
	at com.square.stoic.host.main.HostPluginClient.resolveStagingPluginModule(HostPluginClient.kt:62)
	at com.square.stoic.host.main.HostPluginClient.slowPath(HostPluginClient.kt:81)
	at com.square.stoic.common.PluginClient.run(PluginClient.kt:40)
	at com.square.stoic.host.main.HostPluginRunner.run(HostPluginRunner.kt:8)
	at com.square.stoic.host.main.HostMainKt.wrappedMain(HostMain.kt:84)
	at com.square.stoic.host.main.HostMainKt.main(HostMain.kt:45)
```

It works great after running `adb shell mkdir /data/local/tmp/stoic/dev_jar`.

**Comment by tcmulcahy** [comment]
Thanks for the report - first one that I didn't file myself!
